/**
 * DACM ERP - Global configuration.
 */
const APP = Object.freeze({
  NAME: 'DACM ERP',
  VERSION: '1.0.0',
  COMPANY: 'Dokter AC Mobil',
  DATE_FORMAT: 'dd/MM/yyyy',
  DATETIME_FORMAT: 'dd/MM/yyyy HH:mm:ss',
  DEFAULT_BRANCH: 'D',
  DEFAULT_LANGUAGE: 'id',
  SPREADSHEET_ID: '1feij0mcZiUx_BtZjc0aRusQ_Ott5J4B3v0MslDN90C8'
});

const SHEET = Object.freeze({
  BRANCH: '01_BRANCH', USERS: '02_USERS', ROLES: '03_ROLES',
  CUSTOMERS: '04_CUSTOMERS', VEHICLES: '05_VEHICLES', REGISTER: '06_REGISTER',
  DIAGNOSIS: '07_DIAGNOSIS', APPROVAL: '08_APPROVAL', WORKORDER: '09_WORKORDER',
  QC: '10_QC', INVOICE: '11_INVOICE', PAYMENT: '12_PAYMENT',
  ITEMS: '13_ITEMS', STOCK: '14_STOCK', SUPPLIERS: '15_SUPPLIERS',
  PURCHASE: '16_PURCHASE', LOG: '17_LOG', WORKORDER_ITEMS: '18_WORKORDER_ITEMS'
});

const ROLE = Object.freeze({
  OWNER: 'OWNER', MANAGER: 'MANAGER', FRONT_OFFICE: 'FRONT_OFFICE',
  TECHNICIAN: 'TECHNICIAN', CASHIER: 'CASHIER', WAREHOUSE: 'WAREHOUSE'
});

const DATABASE = Object.freeze({
  HEADER_ROW: 1,
  CACHE_SECONDS: 300,
  TIME_ZONE: Session.getScriptTimeZone() || 'Asia/Jakarta'
});
