/**
 * DACM ERP Configuration
 * Version 1.0
 */

const APP = {
  NAME: "DACM ERP",
  VERSION: "1.0.0",
  COMPANY: "Dokter AC Mobil"
};

const SHEETS = {
  BRANCH: "01_BRANCH",
  USERS: "02_USERS",
  ROLES: "03_ROLES",
  CUSTOMERS: "04_CUSTOMERS",
  VEHICLES: "05_VEHICLES",
  REGISTER: "06_REGISTER",
  DIAGNOSIS: "07_DIAGNOSIS",
  APPROVAL: "08_APPROVAL",
  WORKORDER: "09_WORKORDER",
  QC: "10_QC",
  INVOICE: "11_INVOICE",
  PAYMENT: "12_PAYMENT",
  ITEMS: "13_ITEMS",
  STOCK: "14_STOCK",
  LOG: "15_LOG"
};